#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : autofdo
Version  : 0.15
Release  : 13
URL      : https://github.com/google/autofdo/archive/v0.15.tar.gz
Source0  : https://github.com/google/autofdo/archive/v0.15.tar.gz
Summary  : A C++ application logging library
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0
Requires: autofdo-bin
BuildRequires : libunwind-dev
BuildRequires : llvm-dev
BuildRequires : openssl-dev
BuildRequires : zlib-dev

%description
The %name package contains a library that implements application-level
logging.  This library provides logging APIs based on C++-style
streams and various helper macros.

%package bin
Summary: bin components for the autofdo package.
Group: Binaries

%description bin
bin components for the autofdo package.


%prep
%setup -q -n autofdo-0.15

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1499532381
export CC=clang
export CXX=clang++
export LD=ld.gold
unset LDFLAGS
%reconfigure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1499532381
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/create_gcov
/usr/bin/create_llvm_prof
/usr/bin/dump_gcov
/usr/bin/profile_diff
/usr/bin/profile_merger
/usr/bin/profile_update
/usr/bin/sample_merger
